// GENERATED by `node tools/music.mjs calibrate`: per style, the gain trim (dB) that brings each palette
// voice's stem to its target on a neutral test phrase. Calibrated styles (listened) are never trimmed.
import type { Slot } from "./vocab";
export const VOCAB_TRIM: Record<string, Partial<Record<Slot, number>>> = {
 drive: {
  chords: 5.3,
  lead: 7.4,
  counter: 12,
  bass: 3.1,
  kick: 0.5,
  snare: 8.5,
  arp: 1.2,
  perc: 8.3
 },
 cinematic: {
  chords: 5.2,
  lead: 4.5,
  counter: 12,
  bass: 4.3,
  kick: -4.4,
  arp: 7.4
 },
 ambient: {
  chords: 2.5,
  lead: 1.3,
  counter: 0.8,
  bass: -0.3,
  kick: -2.4,
  arp: 3.1
 },
 folk: {
  chords: 12,
  lead: 12,
  counter: 11.2,
  bass: 1.6,
  kick: -0.5,
  ghost: 9.4,
  arp: 12,
  perc: 12
 },
 playful: {
  chords: 1.7,
  lead: 2.1,
  counter: 12,
  bass: 1.4,
  kick: 0.3,
  snare: 5.1,
  hat: 10.2,
  arp: 12,
  perc: 9.7
 },
 musicBox: {
  chords: 4.7,
  lead: 3.5,
  counter: 4.3,
  bass: 5,
  arp: 3
 },
 nocturne: {
  chords: 12,
  lead: 12,
  counter: 12,
  bass: 6.3
 },
 minimalist: {
  chords: 12,
  lead: 2.1,
  counter: 11.7,
  bass: -3.9,
  arp: 2.5
 },
 jazz: {
  chords: 12,
  lead: 3.8,
  counter: 10.5,
  bass: 0.7,
  kick: 2.8,
  ghost: 10.5,
  hat: 12,
  perc: 11
 },
 lullaby: {
  chords: 3.5,
  lead: 5.3,
  counter: 12,
  bass: 12,
  arp: 12
 },
 chiptune: {
  lead: 7.4,
  bass: -0.8,
  kick: 9.6,
  snare: 10.7,
  arp: 12
 },
 lofi: {
  chords: 10.2,
  lead: 3.5,
  counter: 12,
  bass: -0.1,
  kick: 3.4,
  snare: 9.2,
  ghost: 12,
  hat: 12
 },
 orchestral: {
  chords: 3.6,
  lead: 9.2,
  counter: 0.3,
  bass: 2.9,
  kick: -3.3,
  snare: 8.2,
  arp: 7.4,
  perc: 4.2
 },
 suspense: {
  chords: 5.2,
  lead: 7.3,
  counter: 12,
  bass: -0.1,
  kick: -3.4,
  arp: 8.7,
  perc: 10.4
 },
 rock: {
  chords: 5.1,
  lead: 11.9,
  counter: 12,
  bass: 1.2,
  kick: 1.2,
  snare: 8.2,
  hat: 8.6,
  perc: 7
 },
 hipHop: {
  chords: 12,
  lead: -1.3,
  counter: 12,
  bass: 1.5,
  kick: 1.4,
  snare: 7.2,
  hat: 9.6,
  perc: 9.9
 },
 house: {
  chords: 11.2,
  lead: -0.7,
  counter: 10.9,
  bass: 3.3,
  kick: 1.6,
  snare: 6.7,
  arp: 1.5,
  perc: 7.3
 },
 synthwave: {
  chords: 3.9,
  lead: 11.7,
  counter: 12,
  bass: 2.7,
  kick: 1.4,
  snare: 6.7,
  arp: 1.1,
  perc: 6.2
 },
 world: {
  chords: 4.9,
  lead: 8.7,
  counter: 12,
  bass: -1.6,
  kick: 2.3,
  ghost: 11.5,
  arp: 12
 },
 choral: {
  chords: -7.9,
  lead: -3.1,
  counter: 12,
  bass: 12,
  arp: 12,
  perc: 9.5
 }
};
/** Where a 12 dB trim could not reach the target (long-decaying plucks read low as active RMS), the target moves to where the voice sits. */
export const VOCAB_TARGET_FIX: Record<string, Partial<Record<Slot, number>>> = {
 drive: {
  counter: -3.3
 },
 cinematic: {
  counter: -14.7
 },
 ambient: {},
 folk: {
  chords: -13,
  lead: -2.8,
  arp: -1.9,
  perc: -5.8
 },
 playful: {
  arp: -1.4
 },
 musicBox: {},
 nocturne: {
  chords: -6.3
 },
 minimalist: {
  chords: -11.1
 },
 jazz: {
  chords: -10.5
 },
 lullaby: {
  counter: -4.7,
  bass: -1,
  arp: -4.3
 },
 chiptune: {
  arp: -1.1
 },
 lofi: {
  counter: -7.1,
  ghost: -1.1,
  hat: -13
 },
 orchestral: {},
 suspense: {
  counter: -3
 },
 rock: {
  counter: -7.4
 },
 hipHop: {
  chords: -14.8,
  counter: -4.2
 },
 house: {},
 synthwave: {
  counter: -4.1
 },
 world: {
  counter: -17.1,
  arp: -3.2
 },
 choral: {
  counter: -4.5,
  arp: -2.3
 }
};
